import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const btnStyle = "bg-purple-500 text-center p-3 rounded-xl text-purple-900 font-bold"
  const postStyle = "bg-purple-200 text-purple-950 py-2 px-5 rounded-lg"
  const loaderStyle = "bg-black text-white flex items-center justify-center h-screen w-full"

  const { isSignedIn, user, isLoaded } = useUser()
  const { data } = api.posts.getAll.useQuery()

  if (!isLoaded) {
    return <div className={loaderStyle}>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] gap-5">
        <div>
          <h1 className="text-2xl text-white py-5"> 
            { isSignedIn ? `Welcome ${user.fullName || 'default'}` : "Sign in Here" }
          </h1>
          { !user && <div className={btnStyle}><SignInButton /></div> }
          { !!user && <div className={btnStyle}><SignOutButton /></div> }
        </div>
        { isSignedIn &&
        <div>
          { data?.map( (post) => (
            <div className={postStyle} key={post.id}>
              {post.content}
            </div>
          )) }
        </div>
        }
      </main>
    </>
  );
};

export default Home;
