import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = (props) => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const btnStyle = "bg-purple-500 text-center p-3 rounded-xl text-purple-900 font-bold"
  const { isSignedIn, user, isLoaded } = useUser()

  if (!isLoaded) {
    return <div className={btnStyle}>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          <h1 className="text-2xl text-white py-5"> 
            { isSignedIn ? `Welcome ${user.fullName || 'default'}` : "Sign in Here" }
          </h1>
          { !user && <div className={btnStyle}><SignInButton /></div> }
          { !!user && <div className={btnStyle}><SignOutButton /></div> }
        </div>
      </main>
    </>
  );
};

export default Home;
