import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { useUser } from "@clerk/nextjs";


const SinglePostPage: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Twitter Clone with T3 app - Post Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-full">
        <div>
          Post View
        </div>
      </main>
    </>
  );
};

export default SinglePostPage;
